name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Correr los tests
        id: tests
        run: | 
          set +e 
          output=$(node test/test.js 2>&1)
          exit_code=$?
          echo "$output"
          if [ $exit_code -ne 0 ]; then
            fallos=$(echo "$output" | grep "FALLO")
            curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
            -H 'Content-type: application/json' \
            --data "$(jq -n --arg fallos "$fallos" --arg repo "${{ github.repository }}" --arg sha "${{ github.sha }}" \
              '{text: "❌ Fallaron los tests! No se va a deployar.\nRepositorio: \($repo)\nCommit: \($sha)\n\nDetalle de fallos:\n\($fallos)"}')"
            exit 1
          fi

  sonar:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Obtener el código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #descarga todo el historial de commits

      - name: Análisis de SonarCloud
        uses: SonarSource/sonarcloud-github-action@383f7e52eae3ab0510c3cb0e7d9d150bbaeab838 #v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Paukozak_ing-y-calidad-ci
            -Dsonar.organization=paukozak
            -Dsonar.coverage.exclusions=test/**


  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Obtener el código
        uses: actions/checkout@v4

      - name: Deploy a Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes #npx descarga vercel temporalmente lo ejecuta y lo descarta
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

      - name: Notificar deploy exitoso a Slack
        if: success()
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
          -H 'Content-type: application/json' \
          --data '{"text":"✅ Deploy exitoso a producción!\nRepositorio: ${{ github.repository }}\nCommit: ${{ github.sha }}"}'

      - name: Notificar fallo a Slack
        if: failure()
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
          -H 'Content-type: application/json' \
          --data '{"text":"❌ Falló el pipeline!\nRepositorio: ${{ github.repository }}\nCommit: ${{ github.sha }}"}'